// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCWb-HoN0ZvdZSlkM8rPwiWSsrXhGYAUo',
    appId: '1:768332782498:android:b33d91537df40d3c9a30fb',
    messagingSenderId: '768332782498',
    projectId: 'smart-visitors-log',
    databaseURL: 'https://smart-visitors-log-default-rtdb.firebaseio.com',
    storageBucket: 'smart-visitors-log.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-vjXhFVAh09C78FtpnUMVAqlcBlT1zRE',
    appId: '1:768332782498:ios:b5b16de1f69b13989a30fb',
    messagingSenderId: '768332782498',
    projectId: 'smart-visitors-log',
    databaseURL: 'https://smart-visitors-log-default-rtdb.firebaseio.com',
    storageBucket: 'smart-visitors-log.appspot.com',
    androidClientId: '768332782498-jtee2rgpbk9vtlqq2evhetkgrvg1s37f.apps.googleusercontent.com',
    iosClientId: '768332782498-2c176oki5u9mifsqvusktqgovk907me7.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartvisitorslog.smartvisitorslog',
  );
}
